name: SADEW-MD-WORKFLOW

on:
  workflow_dispatch: # දැන් වැඩ කරන්නේ ඔයා Manual run කළොත් විතරයි. පරණ ඒවා නවතීවි.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install Dependencies
        run: |
          npm install --force
          npm install -g pm2

      - name: Start SADEW-MD
        run: |
          npm start
        env:
          SESSION_ID: ${{ secrets.SESSION_ID }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }} # <--- මේක තමයි අඩුව! දැන් API එක වැඩ කරයි.
